## First function, makeCacheMatrix (be careful with capital letters) returns a 
## matrix of functions allowing to get and set a matrix and its inverse. Second
## function, cacheSolve, takes output of first function and if inverse matrix is informed is
## returned without calculation, if not inverse matrix is calculated and 
## returned, and the matrix generated by makeCacheMatrix is informed.

## makeCacheMatrix creates a matrix containing a function to set the value of
## a matrix, get the value of a matrix, set the value of the inverse matrix 
## and get the value of the inverse matrix. Cols and rows named for clarity.

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinv <- function(inv_mat) inv <<- inv_mat
        getinv <- function() inv        
        mat_func <- matrix(c(set, get, setinv, getinv),nrow=2, ncol=2)
        dimnames(mat_func) <- list(c("set", "get"), c("mat", "inv"))
        mat_func
}

## cacheSolve uses the matrix created by makeCacheMatrix and if inverse matrix
## is informed, returns this inverse matrix, if not, calculates the inverse 
## matrix, informs the inverse in makeCacheMatrix and returns the calculated
## inverse matrix

cacheSolve <- function(x, ...) {
        inv <- x[["get", "inv"]]()
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        data <- x[["get", "mat"]]()
        inv <- solve(data)
        x[["set", "inv"]](inv)
        inv
}
